
project_id = "iiddklelhuszuxpgfmgn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["https://localhost:5173", "http://localhost:5173", "https://127.0.0.1:5173", "https://iiddklelhuszuxpgfmgn.supabase.co"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auto_schema]
enabled = true

[realtime]
enabled = true

[edge_functions]
enabled = true
