// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiddklelhuszuxpgfmgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpZGRrbGVsaHVzenV4cGdmbWduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4ODgxNjgsImV4cCI6MjA1NDQ2NDE2OH0.Zw6fw9IwYATYlenLY6YvPXtGilWXNZeRlTQ0tFg3fes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);